### PR TITLE
Cleanup / modernize this module

### PR DESCRIPTION
**Pull request by nmarley**
This is another big one, and I apologize. But I'm not sure if it makes sense to break it up, esp. given task switching required and limited resources (once we get 👀 on it, might as well fix everything in one fell swoop). This should bring us in to the modern age for this package. This will also necessitate a package rename and a new tag, both of which I'll do once this is merged.

I've rebased + squashed commits logically as well as I think it makes sense, and due to that and the large amount of changes in this case, I would appreciate a merge commit instead of a squash one.

Major changes:

* package rename / uses @dashevo NPM namespace
* remove unused files
* add eslint / linting
* add webpack for bundle build
* run for Node.js 8 + 10 on Travis (previously was 0.10)
* auto-deploy w/tags
* clean up README
* update dependencies

Here's a diffstat showing changes which ignores `package-lock.json`:

```
$ git diff master..cleanup --stat ':(exclude)package-lock.json'
 .coveralls.yml           |   1 -
 .eslintignore            |   1 +
 .eslintrc.yml            |   5 +++
 .gitignore               |  18 ++++----
 .jshintrc                |  44 -------------------
 .npmignore               |  11 +++++
 .travis.yml              |  26 +++++++++---
 CONTRIBUTING.md          |   3 --
 LICENSE                  |  22 ++++++++++
 README.md                |  33 +++++++--------
 bower.json               |  29 -------------
 gulpfile.js              |   8 ----
 index.js                 |   4 +-
 lib/message.js           |  74 ++++++++++++++++----------------
 package.json             |  41 +++++++++++-------
 scripts/travis-deploy.sh |  25 +++++++++++
 test/message.js          | 163 +++++++++++++++++++++++++++++++++--------------------------------------
 webpack.config.js        |  32 ++++++++++++++
 18 files changed, 282 insertions(+), 258 deletions(-)
```

Thanks! Let me know if any questions.

### CODE REVIEW

**Comment by Alex-Werner** [comment]
FYI : Message as Mnemonic are now both retrievable from `@dashevo/dashcore-lib/Message`;

**Comment by nmarley** [comment]
@Alex-Werner Seriously? I searched for this but didn't find it, which is why I put work into this module. 🤦‍♂️ 

Thanks for the info!

**Review by Cofresi — APPROVED** [review]
awesome work!

Even if we have it in dashcore-lib I still think it's great to have this modernized. Some noobs might find it less overwhelming to start looking at this library instead of dashcore-lib if they just want to understand how message signing and verification works.

**Comment by nmarley** [comment]
> Even if we have it in dashcore-lib I still think it's great to have this modernized. Some noobs might find it less overwhelming to start looking at this library instead of dashcore-lib if they just want to understand how message signing and verification works.

Great idea, I agree!

**Pull request merged**
